Java filmorate
yncuk/java-filmorate pull request #1
Opened 2022-11-20 20:19 UTC by yncuk

2022-11-21 20:19 UTC, Donald522 requested changes

2022-11-21 20:19 UTC, Donald522 commented on pom.xml
> +		<dependency>
Советую все тестовые зависимости писать ниже остальных.
Когда их будут десятки - то ориентироваться будет проще

2022-11-21 20:19 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getDescription().length() > 200) {
Код проверки можно вынести в отдельный метод. Сейчас он дублируется в методоах create и update

2022-11-21 20:19 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Советую использовать аннотацию @Value вместо @Data
Она делаем класс неизменяемым. Неизменяемые классы помогают писать более понятный и поддерживаемый код.

2022-11-21 20:19 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        film.setDescription("test test test test test test test test test test test test test test test test test " +
Поскольку у нас уже есть мавен, то буду советовать что-то из сторонних библиотек. Вот например:
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#repeat-char-int-

2022-11-21 20:19 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    // Не совсем понял как писать тесты к полям, которые проверяются по аннотации @Valid
Для этого нужно полностью поднимать контекст приложения в тесте и слать в него http запросы. Как было в прошлом задании с http task manager. Иначе спринговая магия с аннотациями работать не будет - в ней задействовано множество внутренних классов спринга, которые не создаются и не работают, если создать класс вручную через new.
Вот тут рассказано с примером
https://www.baeldung.com/spring-boot-testing

2022-11-21 20:19 UTC, Donald522 commented on .github/workflows/api-tests.yml
> -name: Films API Tests
Почему этот файл удалил?
Автотесты из-за этого не запустились.

2022-11-22 08:48 UTC, yncuk commented
Вернул автотесты, они в ошибку выпадают, не понимаю почему

2022-11-22 08:59 UTC, yncuk commented on .github/workflows/api-tests.yml
> -name: Films API Tests
Вернул автотесты, выдает ошибку, не понимаю почему, пишет "All checks have failed"

2022-11-22 18:20 UTC, yncuk commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    // Не совсем понял как писать тесты к полям, которые проверяются по аннотации @Valid
Понял, это нужно в текущем задании делать?

2022-11-23 20:47 UTC, Donald522 requested changes
А почему удалил файлы
.gitignore, readme, checkstyle, lombok.config?
Они все нужные :)

2022-11-23 20:47 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        user = user.toBuilder().id(id).build();
в Lombok есть аннотация @Wither, с нец будет покороче:
`User userWithId = user.withId(id)`

2022-11-23 20:47 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    // Не совсем понял как писать тесты к полям, которые проверяются по аннотации @Valid
Да. Дальше в сервис будет добавляться функциональность и писать тесты с нуля будет сложнее.
Сейчас мы делаем каркас сервиса и надо сразу сделать каркас тестов.

Вообще говоря, иногда тесты пишут перед написанием кода. Такой подход называется TDD - test driven development.

2022-11-23 20:49 UTC, Donald522 commented on .github/workflows/api-tests.yml
> -name: Films API Tests
Сходу тоже не понял.
Думаю для начала надо вернуть все удаленные файлы.
Вот здесь я нашел скрипт сборки, может поможет разобраться
https://github.com/yandex-praktikum/java-filmorate/blob/ci/.github/workflows/api-tests.yml

2022-11-24 16:41 UTC, yncuk commented on .github/workflows/api-tests.yml
> -name: Films API Tests
Оказалось не тот путь указан -_- 
теперь нет ошибки

2022-11-26 19:05 UTC, Donald522 requested changes
Отказываться от Lombok не стоит. Лучше разобраться, что там в тестах не работало.
С автопроверкой кажется не в этом проблема. С путем все было хорошо.

2022-11-26 19:05 UTC, Donald522 commented on pom.xml
> +		<dependency>
А зачем и gson и jackson?
Это библиотеки для решения одной и той же задачи. 
Надо выбрать что-то одно. Де факто стандартом является jackson.

2022-11-26 19:05 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        mockMvc = MockMvcBuilders.standaloneSetup(filmController)
Это лишнее.
У тебя же поле mockMvc помечено аннотацией Autowired, spring сам разберется с его инициализацией

2022-11-26 19:05 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
>          filmController = new FilmController();
Тут тоже самое, лучше добавить Autowired над полем filmController
Такой тест в том числе должен проверять и правильность конфигурации, что контекст приложение правильно сконфигурирован и что приложение стартует.

2022-11-26 19:05 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film { // пришлось уйти от аннотаций Value и Builder, а то никак не получалось тесты настроить
А что не получалось?
Писать геттеры и сеттеры вручную не нужно.
К тому же, аннотация Value дает не тольо их. То есть твоя замена не равнозначна.
https://projectlombok.org/features/Value

2022-11-26 19:05 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/mapper/CustomMapper.java
> +    public static ObjectMapper getMapper() { // Это наставник подсказал
Тут важно, чтобы такая настройка в тестах соответствовала спецификации API кода твоего приложения.

Например, если какое-то поле из DTO класса не попадет в json из-за того, что оно null, то приложение не должно из-за этого упасть.

2022-11-26 19:05 UTC, Donald522 commented on .github/workflows/api-tests.yml
> +    uses: java-filmorate/.github/workflows/api-tests.yml@ci
Ну нет :)
Если ты посмотришь на вкладку Checks, то там написано, что ни однав джоба не запустилась.
Путь был правильный.

2022-11-27 11:24 UTC, yncuk commented on pom.xml
> +		<dependency>
Забыл убрать gson

2022-11-27 12:05 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film { // пришлось уйти от аннотаций Value и Builder, а то никак не получалось тесты настроить
Ругалось на отсутствие конструктора или креатора: 
`Cannot construct instance of ru.yandex.practicum.filmorate.model.Film (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)`
подсказали про аннтоацию JsonCreator

2022-12-02 11:54 UTC, merged