<fix>: <Добавить ErrorHandler, добавить интерфейсы FilmStorage и User…
yncuk/java-filmorate pull request #3
Opened 2022-12-06 20:19 UTC by yncuk

…Storage, и их имплементацию в памяти, дописать запросы в контроллерах, добавить сервисы для пользователей и фильмов>

2022-12-06 20:21 UTC, yncuk commented
Вопрос, в задании не указано, нужно ли писать свои тесты, писать их по покрытию кода смотреть ?
и насчет логов, нужно ли логировать всю информацию?

2022-12-06 20:24 UTC, yncuk commented
И второй вопрос насчет логов, нужно ли логировать всю информацию или частично что то?

2022-12-07 17:24 UTC, Donald522 requested changes
Привет!
В целом все нормально.

Надо добавить тесты.

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    FilmStorage filmStorage;
Поля должна быть `private final`

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public FilmController(FilmStorage filmStorage, FilmService filmService) {
В Lombok есть аннотация `@RequiredArgsContructor`
Спринг позволяет не писать `@Autowired` при единственном конструкторе.

Итого можно просто добавить аннотацию на класс и не писать boilerplate конструкторы

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    UserStorage userStorage;
Тожк самое что в FilmController

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +public class ErrorResponse {
Давай добавим аннотацию `@Value`
Зачем писать конструкторы и геттеры

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Comparator<Film> comparator = (o1, o2) -> {
Это надо вынести в константу
Зачем создать новый объект на каждый вызов?

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Long> friends;
Можно дефолтным значением сделать пустое множество, чтобы не проверять потом на null

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Long> likes;
А почему такое решение?
Зачем на фильме информация, кто его полайкал?

Вспомни как выглядят видеохостинге, например ютуб.
На видео есть просто кол-во лайков. А у пользователя в профиле есть список понравившихся видосиков.

Лучше тут иметь просто int с кол-вом лайков, а у пользователя set понравившихся фильмов.

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return convertSetIdToListUsers(friends.stream().filter(friends2::contains).collect(Collectors.toSet()));
Есть метод retainAll у интерфейса Set

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void addFriendMethod(Integer id, Integer friendId) throws NotFoundException, ValidationException {
Runtime исключения не обязательно добавлять в сигнатуру.
Замусоривает код.

2022-12-07 17:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        validating(user);
Логику валидации лучше вынести выше.
В контроллер либо в сервис.

2022-12-07 17:25 UTC, Donald522 commented
> Привет, Вопрос, в задании не указано, нужно ли писать свои тесты, писать их по покрытию кода смотреть ?

Таких вопросов стоять не должно.
Код без тестов не принимается. Написание тестов это часть любой задачи.

2022-12-07 17:26 UTC, Donald522 commented
> И второй вопрос насчет логов, нужно ли логировать всю информацию или частично что то?

Тут нет четкого ответа.
Логировать нужно так, чтобы в случае проблем было понятно, что произошло.

2022-12-12 14:46 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Long> friends;
А как потом его изменять?

2022-12-12 14:49 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return convertSetIdToListUsers(friends.stream().filter(friends2::contains).collect(Collectors.toSet()));
Немного не понял как использовать retainAll, он перезаписывает поле друзья и тесты постмана валятся

2022-12-13 17:59 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmStorage filmStorage;
FilmStorage убираем из контроллера. В контроллере только сервис, все методы хранилища вызываем только в сервисе

2022-12-13 17:59 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmStorage.findAll();
в сервис

2022-12-13 17:59 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmStorage.findById(id);
в сервис

2022-12-13 17:59 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final UserStorage userStorage;
аналогично комментарию выше

2022-12-13 17:59 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return userStorage.findAll();
в сервис

2022-12-13 17:59 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return userStorage.findById(id);
в сервис

2022-12-13 17:59 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return userStorage.giveFriends(id);
в сервис

2022-12-13 17:59 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/NotFoundException.java
> +public class NotFoundException extends Exception {
лучше EntityNotFoundException, так более понятно описывает его назначение

2022-12-13 17:59 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/handler/ErrorHandler.java
> +public class ErrorHandler {
Было бы неплохо добавить сюда логирование и выводить ошибки в log.error  или log.debug

2022-12-14 19:10 UTC, yncuk commented
Привет, доработал по замечаниям

2022-12-19 07:59 UTC, merged