<feat>: <Добавить зависимости в pom для работы с базами данных>
yncuk/java-filmorate pull request #5
Opened 2022-12-25 19:35 UTC by yncuk

2023-01-09 08:44 UTC, Donald522 requested changes
Привет!

С Новым годом)

Хорошая работа. Некоторые места можно еще поправить, например в классе Film для жанра сделать отдельный класс.

Еще я бы переписал метод giveMostPopularFilm. Нет нужды вытаскивать всю базу в приложение, чтобы потом выбросить большую часть. Сделать сортировку и limit лучше прям в базе, тем более, что у тебя в таблице FILM есть поле специальное.

2023-01-09 08:44 UTC, Donald522 commented on src/main/resources/schema.sql
> +create table IF NOT EXISTS USERS
При такой схеме, отсутствует уникальность по логинам.
Если мы захотим потом добавить вход с паролем, то это не получится сделать.

2023-01-09 08:44 UTC, Donald522 commented on src/main/resources/schema.sql
> +    FILM_NAME    CHARACTER VARYING      not null,
Обычно пишут varchar

2023-01-09 08:44 UTC, Donald522 commented on src/main/resources/schema.sql
> +    FILM_GENRE_ID INTEGER auto_increment
Здесь лучше сделать ключом пару (film_id, genre_id)
Иначе могут быть дубликаты (когда одному фильму несколько раз дан один и тот же жанр, например), с которыми придется справляться на уровне кода.

2023-01-09 08:44 UTC, Donald522 commented on src/main/resources/schema.sql
> +    LIKED_FILM_ID INTEGER auto_increment
Тоже самое, если на пару (user_id, film_id) нет ограничения уникальности, то пользователь может бесконечно айкать один и тот же фильм, что неправильно.

2023-01-09 08:44 UTC, Donald522 commented on src/main/resources/schema.sql
> +    PRIMARY_ID INTEGER auto_increment,
Тоже самое, в маппинг-таблицах нет ценности в собственных id.

2023-01-09 08:44 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    LinkedHashSet<Mpa> genres;
А почему жанр это mpa?

2023-01-09 08:44 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    @NotNull @NotBlank Integer id;
NotBlank не включает в себя NotNull?

2023-01-09 08:44 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "insert into films (film_name, description, release_date, duration, rate) values (?, ?, ?, ?, ?)";
Лучше давать понятные имена переменным

2023-01-09 08:44 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql3 = "select * from films where film_name = ? and description = ? and release_date = ? and duration = ?";
Есть такая штука: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/support/GeneratedKeyHolder.html

Она позволяет не доставать id отдельным запросом

2023-01-09 08:44 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (jdbcTemplate.query(sql, this::makeId, id).isEmpty()) {
Зачем делать 2 запроса?
Можно сделать один и понять, вернулось что-то или нет.
Поход в базу это очень дорогая операция.

2023-01-09 08:44 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Film makeFilm(ResultSet rs, Integer rowNum) throws SQLException {
Лучше вынести в RowMapper

2023-01-09 08:44 UTC, Donald522 commented on src/main/resources/schema.sql
> +    STATUS     BOOLEAN default FALSE not null,
А что означает это поле?

2023-01-09 08:44 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "select users.user_id, users.email, users.login, users.user_name, users.birthday, friend.friend_id from friend join users on friend.friend_id = users.user_id where friend.user_id
А в чем смысл группировки по уникальному значению?

2023-01-09 08:44 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "select liked_film.film_id from liked_film join users on liked_film.user_id = users.user_id where liked_film.user_id = ? group by users.user_id";
Тоже не понятно зачем группировка

2023-01-09 08:44 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +               @JsonProperty("name") String name) {
Если это ограниченный набор значений, то может имеет смысл сделать enum?

2023-01-09 17:06 UTC, yncuk commented on src/main/resources/schema.sql
> +    FILM_GENRE_ID INTEGER auto_increment
в теории было про искусственные ключи и не сразу понял, как сделать пару ключей, немного запутался)

2023-01-09 17:19 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    @NotNull @NotBlank Integer id;
Для integer можно оставить NotNull, а для строк тогда NotBlank

2023-01-09 17:38 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql3 = "select * from films where film_name = ? and description = ? and release_date = ? and duration = ?";
Да, я ее хотел использовать, но подумал почему то, что это не нужно тут

2023-01-09 18:20 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (jdbcTemplate.query(sql, this::makeId, id).isEmpty()) {
По заданию и тестам, если фильм или пользователь не найден, нужно бросить 404 ошибку, если оставить один запрос через makeFilm, то если фильма нет, то выпадет 500 ошибка перед обработкой EntityNotFoundException

2023-01-09 18:21 UTC, yncuk commented on src/main/resources/schema.sql
> +    STATUS     BOOLEAN default FALSE not null,
По заданию это поле отмечает статус дружбы у двух пользователей, но мне кажется, с моей схемой он не нужен, на всякий случай оставил, на будущее

2023-01-09 18:24 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "select users.user_id, users.email, users.login, users.user_name, users.birthday, friend.friend_id from friend join users on friend.friend_id = users.user_id where friend.user_id
видимо писал другой запрос до этого, там ругалось, что нужно обязательно добавить, забыл удалить)

2023-01-09 18:24 UTC, yncuk commented
Привет, и тебя с Новым годом)

2023-01-09 19:28 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +               @JsonProperty("name") String name) {
Пробовал енам сделать, что то не получилось, попробую еще разок

2023-01-09 19:35 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +               @JsonProperty("name") String name) {
не получается из-за тире "-", в тестах постмана это обязательно, и в чате советовали сделать класс Mpa

2023-01-09 19:38 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    LinkedHashSet<Mpa> genres;
реализация одинаковая, даже не подумал, что не так))

2023-01-09 19:50 UTC, yncuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Film makeFilm(ResultSet rs, Integer rowNum) throws SQLException {
а как быть с методами makeGenresForFilm и makeMpaForFilm
не понял, как их перенести в Row Mapper

2023-01-10 19:19 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Film makeFilm(ResultSet rs, Integer rowNum) throws SQLException {
В идеале нужно доставать фильм одним запросом в базу.
Вот хороший пример:
https://stackoverflow.com/questions/16461735/jdbc-template-one-to-many

Думаю, что это опционально, если есть время и желание.

2023-01-10 19:19 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (jdbcTemplate.query(sql, this::makeId, id).isEmpty()) {
А что за ошибка происходит через makeFilm? У тебя же запрос один и тот же выполняется.
Может дело в разных методах jdbcTemplate?

2023-01-10 19:41 UTC, Donald522 approved these changes
Привет!

Сейчас все норм, насчет маппера ответил

2023-01-13 13:44 UTC, merged